# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "pandas",
#   "unidecode",
# ]
# ///

import argparse
import pandas as pd
import unidecode

# Example of a record in the output
# - name: "X X"
#   title: "X"
#   linkedin: "https://www.linkedin.com/in/X"
#   x: ""
#   image: "images/optimized/organizers-300x300/X.webp"

parser = argparse.ArgumentParser(description="Convert organizers CSV to YAML for the website.")
parser.add_argument("file", help="Path to the input CSV file")
parser.add_argument("-o", "--output", default="organizers.yml", help="Path to the output YAML file (default: organizers.yml)")
args = parser.parse_args()

# Load the CSV file
df = pd.read_csv(args.file)

# Clean the column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_', regex=False).str.replace('(', '', regex=False).str.replace(')', '', regex=False)
df.columns = [unidecode.unidecode(column) for column in df.columns]

# df = df.drop(columns=['numer_telefonu', 'nazwa_pliku_ze_zdjeciem', 'mail_firmowy', 'mail_prywatny/kontaktowy'])
# Drop the columns that are not needed
df = df[['imie', 'nazwisko', 'pelna_nazwa_roli_autogenerated', 'linkedin', 'x', 'kolejnosc_www']]

# Drop rows with missing name fields
df = df.dropna(subset=['imie', 'nazwisko', 'pelna_nazwa_roli_autogenerated'])

# Sort the data frame by the order on the website
df = df.sort_values(by=['kolejnosc_www', 'nazwisko'])

# Write the data to the YAML file
with open(args.output, "w") as f:
    for i, row in df.iterrows():
        image_name = unidecode.unidecode(row['imie'] + row['nazwisko']).replace(' ', '')
        record = {
            'name': row['imie'].strip() + ' ' + row['nazwisko'].strip(),
            'title': row['pelna_nazwa_roli_autogenerated'],
            'linkedin': row.linkedin if pd.notna(row.linkedin) else '',
            'x': row.x if pd.notna(row.x) else '',
            'image': f'images/optimized/organizers-300x300/{image_name}.webp'
        }
        for j, (key, value) in enumerate(record.items()):
            if j == 0:
                f.write("- ")
            else:
                f.write("  ")
            f.write(f"{key}: \"{value}\"\n")
        f.write("\n")
    
print(f"Written {len(df)} organizers to {args.output}")
